apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil42
  labels:
    app: wil42
spec:
  rules:
  - host: "wil42.localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil42-service
            port:
              number: 8888
